            - nombre: Qodana Scan
  # Puedes anclar al commit exacto o a la versi√≥n.
  # usos: JetBrains/qodana-action@27de2a744479d1d731934eeaf79287575ebc5dd3
  usos: JetBrains/qodana-action@v2025.2.1
  con:
    Argumentos adicionales de la CLI de Qodana. Separe los argumentos con comas (`,`).
    args: # opcional, el valor predeterminado es
    # Directorio para almacenar los resultados del an√°lisis
    results-dir: # opcional, el valor predeterminado es ${{ runner.temp }}/qodana/results
    # Directorio para almacenar cach√©s de Qodana
    cache-dir: # opcional, el valor predeterminado es ${{ runner.temp }}/qodana/caches
    # Restaurar y guardar autom√°ticamente los cach√©s de Qodana usando los cach√©s de GitHub
    use-caches: # opcional, el valor predeterminado es verdadero
    # Establecer la clave de cach√© principal
    primary-cache-key: # opcional, el valor predeterminado es qodana-2025.2-${{ github.ref }}-${{ github.sha }}
    # Establecer la clave de cach√© adicional
    clave de cach√© adicional: # opcional, el valor predeterminado es qodana-2025.2-${{ github.ref }}
    # Cargar cach√© solo para la rama predeterminada
    cache-default-branch-only: # opcional, el valor predeterminado es falso
    # Cargar resultados de Qodana (SARIF, otros artefactos, registros) como un artefacto en el trabajo
    upload-result: # opcional, el valor predeterminado es falso
    # Especifique el nombre del artefacto de resultados de Qodana, utilizado para cargar los resultados
    nombre-del-artefacto: # opcional, el valor predeterminado es qodana-report
    # Use anotaciones para marcar los resultados en la interfaz de usuario de GitHub
    use-annotations: # opcional, el valor predeterminado es verdadero
    # Analizar S√ìLO los archivos modificados en una solicitud de extracci√≥n
    pr-mode: # opcional, el valor predeterminado es verdadero
    # Publicar un comentario con el resumen de los resultados de Qodana en la solicitud de extracci√≥n
    post-pr-comment: # opcional, el valor predeterminado es verdadero
    # Token de GitHub para acceder al repositorio: anotaciones de publicaciones, comentarios
    github-token: # opcional, el valor predeterminado es ${{ github.token }}
    # Env√≠a correcciones de Qodana al repositorio, puede ser ninguna, una rama a la rama actual o una solicitud de extracci√≥n
    push-fixes: # opcional, el valor predeterminado es ninguno
    # Mensaje de confirmaci√≥n para la confirmaci√≥n con correcciones r√°pidas. No se usa si `push-fixes` est√° configurado como `none`.
    commit-message: # opcional, el valor predeterminado es ü§ñ Aplicar soluciones r√°pidas de Qodana
    # Utilice la CLI inestable de Qodana todas las noches
    use-nightly: # opcional, el valor predeterminado es falso
          
